import type { Lang } from "./i18n";

type NameMap = Record<string, string>;

const fr: NameMap = {
  algeria: "Algérie",
  angola: "Angola",
  benin: "Bénin",
  botswana: "Botswana",
  "burkina-faso": "Burkina Faso",
  burundi: "Burundi",
  "cabo-verde": "Cap-Vert",
  cameroon: "Cameroun",
  "central-african-republic": "République centrafricaine",
  chad: "Tchad",
  comoros: "Comores",
  "congo-brazzaville": "Congo (Brazzaville)",
  "congo-kinshasa": "Congo (Kinshasa)",
  "cote-divoire": "Côte d'Ivoire",
  djibouti: "Djibouti",
  egypt: "Égypte",
  "equatorial-guinea": "Guinée équatoriale",
  eritrea: "Érythrée",
  eswatini: "Eswatini",
  ethiopia: "Éthiopie",
  gabon: "Gabon",
  gambia: "Gambie",
  ghana: "Ghana",
  guinea: "Guinée",
  "guinea-bissau": "Guinée-Bissau",
  kenya: "Kenya",
  lesotho: "Lesotho",
  liberia: "Libéria",
  libya: "Libye",
  madagascar: "Madagascar",
  malawi: "Malawi",
  mali: "Mali",
  mauritania: "Mauritanie",
  mauritius: "Maurice",
  morocco: "Maroc",
  mozambique: "Mozambique",
  namibia: "Namibie",
  niger: "Niger",
  nigeria: "Nigéria",
  rwanda: "Rwanda",
  "sao-tome-and-principe": "Sao Tomé-et-Principe",
  senegal: "Sénégal",
  seychelles: "Seychelles",
  "sierra-leone": "Sierra Leone",
  somalia: "Somalie",
  "south-africa": "Afrique du Sud",
  "south-sudan": "Soudan du Sud",
  sudan: "Soudan",
  tanzania: "Tanzanie",
  togo: "Togo",
  tunisia: "Tunisie",
  uganda: "Ouganda",
  zambia: "Zambie",
  zimbabwe: "Zimbabwe",
};

const de: NameMap = {
  algeria: "Algerien",
  angola: "Angola",
  benin: "Benin",
  botswana: "Botswana",
  "burkina-faso": "Burkina Faso",
  burundi: "Burundi",
  "cabo-verde": "Kap Verde",
  cameroon: "Kamerun",
  "central-african-republic": "Zentralafrikanische Republik",
  chad: "Tschad",
  comoros: "Komoren",
  "congo-brazzaville": "Kongo (Brazzaville)",
  "congo-kinshasa": "Kongo (Kinshasa)",
  "cote-divoire": "Elfenbeinküste",
  djibouti: "Dschibuti",
  egypt: "Ägypten",
  "equatorial-guinea": "Äquatorialguinea",
  eritrea: "Eritrea",
  eswatini: "Eswatini",
  ethiopia: "Äthiopien",
  gabon: "Gabun",
  gambia: "Gambia",
  ghana: "Ghana",
  guinea: "Guinea",
  "guinea-bissau": "Guinea-Bissau",
  kenya: "Kenia",
  lesotho: "Lesotho",
  liberia: "Liberia",
  libya: "Libyen",
  madagascar: "Madagaskar",
  malawi: "Malawi",
  mali: "Mali",
  mauritania: "Mauretanien",
  mauritius: "Mauritius",
  morocco: "Marokko",
  mozambique: "Mosambik",
  namibia: "Namibia",
  niger: "Niger",
  nigeria: "Nigeria",
  rwanda: "Ruanda",
  "sao-tome-and-principe": "São Tomé und Príncipe",
  senegal: "Senegal",
  seychelles: "Seychellen",
  "sierra-leone": "Sierra Leone",
  somalia: "Somalia",
  "south-africa": "Südafrika",
  "south-sudan": "Südsudan",
  sudan: "Sudan",
  tanzania: "Tansania",
  togo: "Togo",
  tunisia: "Tunesien",
  uganda: "Uganda",
  zambia: "Sambia",
  zimbabwe: "Simbabwe",
};

const es: NameMap = {
  algeria: "Argelia",
  angola: "Angola",
  benin: "Benín",
  botswana: "Botsuana",
  "burkina-faso": "Burkina Faso",
  burundi: "Burundi",
  "cabo-verde": "Cabo Verde",
  cameroon: "Camerún",
  "central-african-republic": "República Centroafricana",
  chad: "Chad",
  comoros: "Comoras",
  "congo-brazzaville": "Congo (Brazzaville)",
  "congo-kinshasa": "Congo (Kinshasa)",
  "cote-divoire": "Costa de Marfil",
  djibouti: "Yibuti",
  egypt: "Egipto",
  "equatorial-guinea": "Guinea Ecuatorial",
  eritrea: "Eritrea",
  eswatini: "Esuatini",
  ethiopia: "Etiopía",
  gabon: "Gabón",
  gambia: "Gambia",
  ghana: "Ghana",
  guinea: "Guinea",
  "guinea-bissau": "Guinea-Bisáu",
  kenya: "Kenia",
  lesotho: "Lesoto",
  liberia: "Liberia",
  libya: "Libia",
  madagascar: "Madagascar",
  malawi: "Malaui",
  mali: "Malí",
  mauritania: "Mauritania",
  mauritius: "Mauricio",
  morocco: "Marruecos",
  mozambique: "Mozambique",
  namibia: "Namibia",
  niger: "Níger",
  nigeria: "Nigeria",
  rwanda: "Ruanda",
  "sao-tome-and-principe": "Santo Tomé y Príncipe",
  senegal: "Senegal",
  seychelles: "Seychelles",
  "sierra-leone": "Sierra Leona",
  somalia: "Somalia",
  "south-africa": "Sudáfrica",
  "south-sudan": "Sudán del Sur",
  sudan: "Sudán",
  tanzania: "Tanzania",
  togo: "Togo",
  tunisia: "Túnez",
  uganda: "Uganda",
  zambia: "Zambia",
  zimbabwe: "Zimbabue",
};

const maps: Record<Lang, NameMap | null> = { en: null, fr, de, es };

export function localizedCountryName(slug: string, fallback: string, lang: Lang): string {
  const m = maps[lang];
  return (m && m[slug]) || fallback;
}
