export type CountryRecord = {
  slug: string;
  name: string;
  code: string;
};

export const africanCountries: CountryRecord[] = [
  { slug: "algeria", name: "Algeria", code: "DZ" },
  { slug: "angola", name: "Angola", code: "AO" },
  { slug: "benin", name: "Benin", code: "BJ" },
  { slug: "botswana", name: "Botswana", code: "BW" },
  { slug: "burkina-faso", name: "Burkina Faso", code: "BF" },
  { slug: "burundi", name: "Burundi", code: "BI" },
  { slug: "cabo-verde", name: "Cabo Verde", code: "CV" },
  { slug: "cameroon", name: "Cameroon", code: "CM" },
  { slug: "central-african-republic", name: "Central African Republic", code: "CF" },
  { slug: "chad", name: "Chad", code: "TD" },
  { slug: "comoros", name: "Comoros", code: "KM" },
  { slug: "congo-brazzaville", name: "Congo (Brazzaville)", code: "CG" },
  { slug: "congo-kinshasa", name: "Congo (Kinshasa)", code: "CD" },
  { slug: "cote-divoire", name: "Côte d'Ivoire", code: "CI" },
  { slug: "djibouti", name: "Djibouti", code: "DJ" },
  { slug: "egypt", name: "Egypt", code: "EG" },
  { slug: "equatorial-guinea", name: "Equatorial Guinea", code: "GQ" },
  { slug: "eritrea", name: "Eritrea", code: "ER" },
  { slug: "eswatini", name: "eSwatini", code: "SZ" },
  { slug: "ethiopia", name: "Ethiopia", code: "ET" },
  { slug: "gabon", name: "Gabon", code: "GA" },
  { slug: "gambia", name: "Gambia", code: "GM" },
  { slug: "ghana", name: "Ghana", code: "GH" },
  { slug: "guinea", name: "Guinea", code: "GN" },
  { slug: "guinea-bissau", name: "Guinea-Bissau", code: "GW" },
  { slug: "kenya", name: "Kenya", code: "KE" },
  { slug: "lesotho", name: "Lesotho", code: "LS" },
  { slug: "liberia", name: "Liberia", code: "LR" },
  { slug: "libya", name: "Libya", code: "LY" },
  { slug: "madagascar", name: "Madagascar", code: "MG" },
  { slug: "malawi", name: "Malawi", code: "MW" },
  { slug: "mali", name: "Mali", code: "ML" },
  { slug: "mauritania", name: "Mauritania", code: "MR" },
  { slug: "mauritius", name: "Mauritius", code: "MU" },
  { slug: "morocco", name: "Morocco", code: "MA" },
  { slug: "mozambique", name: "Mozambique", code: "MZ" },
  { slug: "namibia", name: "Namibia", code: "NA" },
  { slug: "niger", name: "Niger", code: "NE" },
  { slug: "nigeria", name: "Nigeria", code: "NG" },
  { slug: "rwanda", name: "Rwanda", code: "RW" },
  { slug: "sao-tome-and-principe", name: "Sao Tome and Principe", code: "ST" },
  { slug: "senegal", name: "Senegal", code: "SN" },
  { slug: "seychelles", name: "Seychelles", code: "SC" },
  { slug: "sierra-leone", name: "Sierra Leone", code: "SL" },
  { slug: "somalia", name: "Somalia", code: "SO" },
  { slug: "south-africa", name: "South Africa", code: "ZA" },
  { slug: "south-sudan", name: "South Sudan", code: "SS" },
  { slug: "sudan", name: "Sudan", code: "SD" },
  { slug: "tanzania", name: "Tanzania", code: "TZ" },
  { slug: "togo", name: "Togo", code: "TG" },
  { slug: "tunisia", name: "Tunisia", code: "TN" },
  { slug: "uganda", name: "Uganda", code: "UG" },
  { slug: "zambia", name: "Zambia", code: "ZM" },
  { slug: "zimbabwe", name: "Zimbabwe", code: "ZW" }
];
